---
title: "DISCRETISATION"
author: "Anna MAUCLET"
date: "30/03/2022"
output: html_document

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
knitr::opts_chunk$set(eval = TRUE)
knitr::opts_chunk$set(warning = FALSE)
```

# Je commence par télécharger mes library sf et mapsf
Je vérifie avec la commande setwd que je me trouve au bon endroit
Puis, j'utilise les commandes st read et read.csv pour lire mes fichiers.

```{r}
library(sf)
library(mapsf)
setwd("C:/Users/HP/Documents/R/DISCRETISATION")
st_read("vote.gpkg")
```
```{r}
read.csv("bondyInsee.csv")
```

Je donne un nom à mon fichier, puis je regarde sa structure 
```{r}
data <- read.csv("bondyInsee.csv")
str(data)
```
# Reprise des données sur le nombre de ménages et discrétisation 
```{r}
summary(data$Men_pauv)
hist(data$Men_pauv, breaks = c(0,5,10,20,40,200,300))
```
Création d'un histogramme 
```{r}
png(height = 800, width = 600, filename = "Anna.png")
hist(data$Men_pauv, breaks = c(0,5,10,20,40,200,300))
dev.off()
```
```{r}
summary(data$Men_prop)
hist(data$Men_prop, breaks = c(0,5,10,20,40,200,300))
png(height = 800, width = 600, filename = "Anna2.png")
hist(data$Men_prop, breaks = c(0,5,10,20,40,200,300))
dev.off()
```

