---
title: "script 2"
author: "Anna MAUCLET"
date: "14/04/2022"
output:
  html_document:
	number_sections: yes
	toc: yes
editor_options:
  chunk_output_type: console
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
knitr::opts_chunk$set(cache = TRUE)
knitr::opts_chunk$set(eval = TRUE)
knitr::opts_chunk$set(warning = FALSE)
```

```{r}
library(sf)
library(mapsf)
data <- st_read("vote.gpkg", "jointure")
read.csv("bondyInsee.csv")
```
# Carte de vote - HERVE


```{r}
apply(data [,14:18, drop = T], 2,sum)
summary(data[,14:15, drop = T])
data <- data [,15]
names (data) [1] <- c("HERVE")
palette <- heat.colors(5, rev = T)
seuils <- c(85, 100, 125, 150, 175, 230)
str(data)
png("resultHERVE.png", width = 4000, height = 4000, res = 400)
mf_choro(data,  var = "HERVE", breaks = seuils, pal = palette,border = NA, leg_pos = "n")
mf_label(data, "HERVE")
mf_inset_on(data, pos = "topright")
par(mar = c(2,2,2,2))
hist(data$HERVE, border = NA, right = F, col=palette, main = "", xlab = "", ylab="")
mf_inset_off()
dev.off()
```

Je charge la library png pour aider à l'affichage de la carte de vote HERVE.
```{r}
library("png")
img1<-readPNG("resultHERVE.png")
display<-function(...){
  imageList<-list(...) ;   totalWidth<-0 ;   maxHeight<-0 ;   
for (img in imageList){    if(is.character(img)) img<-readPNG(img) ;  dimg<-dim(img) ;  totalWidth<-totalWidth+dimg[2] ;   maxHeight<-max(maxHeight,dimg[1])  }
  par(mar=c(0,0,0,0)) ;   plot(c(0,totalWidth),c(0,maxHeight),type="n",asp=1,xaxt="n",yaxt="n",xlab="x",ylab="y") ;   offset<-0 ; 
  for (img in imageList){    dimg<-dim(img) ;    rasterImage(img,offset,0,offset+dimg[2],dimg[1])
    offset<-offset+dimg[2]  }}
display(img1)
```


# Carroyage 
## Choix de la variable

J'ai choisi la variable des ménages propriétaires afin d'étudier leur localisation à Bondy. 
```{r}
pal <- colorNumeric(
  palette = "YlOrRd",
  domain = data$Taux.de.participation....
)
leaflet(data) %>%
  addPolygons(color = "#444444", weight = 1, smoothFactor = 0.5,
    opacity = 1.0, fillOpacity = 0.5,
    fillColor = ~colorQuantile("YlOrRd", Men_prop)(Men_prop),
    highlightOptions = highlightOptions(color = "white", weight = 2,
      bringToFront = TRUE)) %>% addLegend("bottomright", pal = pal, values = ~Nb.votes.nuls,
    title = "Ménages propriétaires",
    opacity = 1
  ) %>% addTiles()
```

